### PR TITLE
Use same auth mechanisms as on lettres

### LINKED ISSUE #12: L'authentification ne fonctionne pas correctement
Le système d'authentification par token actuel ne fonctionne pas correctement (tokens dont l'obsolescence n'est pas détectée par le frontend, localStorage mal géré, etc) et mérite d'être revu tant côté backend que frontend.

Dans l'optique d'uniformiser l'implémentation de l'authentification à travers nos différents projets, je propose s'inspirer de l'implémentation de [https://github.com/chartes/lettres-vue](https://github.com/chartes/lettres-vue) et de [https://github.com/chartes/lettres-app](https://github.com/chartes/lettres-app) qui est de meilleure qualité.

**Objectifs :**
- Un système d'authentification pleinemnent fonctionnel (login, logout) et compatible avec les comptes utilisateurs déjà existants
- Une implémentation similaire (mêmes bibliothèques js & python) à celle du projet Lettres (sauf si bug détecté, évidemment)
- Une rétrocompatibilité avec les comptes utilisateurs existants

### PR DESCRIPTION
**Pull request by fbessou**
Closes #12.

### CODE REVIEW

**Comment by MrGecko** [comment]
Don't you need to update the backend side?

**Comment by MrGecko** [comment]
> Don't you need to update the backend side?

Okay i can see the backend fork now: GitHub updates are sometime misleading :)

**Comment by MrGecko** [comment]
@fbessou when you enter wrong credentials you are automatically routed to the home page and you can't see the error message anymore.

**Comment by fbessou** [comment]
Ok, I will fix that. There is probably the same problem on Lettres then since I adapted Adele to match the behaviour of Lettres.

**Comment by fbessou** [comment]
Fixed :)

**Pull request merged**
